// Score label mapping
export const scoreLabels = {
  composition: { ko: "구도", en: "Composition", icon: "📐" },
  lighting: { ko: "노출/빛", en: "Lighting", icon: "💡" },
  color: { ko: "색감", en: "Color", icon: "🎨" },
  focus: { ko: "초점/심도", en: "Focus", icon: "🔍" },
  storytelling: { ko: "스토리텔링", en: "Storytelling", icon: "📖" },
  timing: { ko: "타이밍", en: "Timing", icon: "⏱" },
  postProcessing: { ko: "후보정", en: "Post-processing", icon: "🖥" }
};

// Categories are now dynamically generated by AI
// This is kept for backward compatibility
export const categories = ["전체"];
